name: testflow
 
on:
  workflow_run:
    workflows: [ triggerflow ]    
    types: 
      - requested

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        run: echo test
